@startsalt
{
{+
  <color:green>DroneEntrega
  <color:white> space
  Mamma Jamma - Barra
  Detalhes do Pedido
  ---------------------------
  Pedido: #12345
  Enedereco: Ibmec Sala 305
  <color:white> space
  Commanda:
  {T
  +Panino di Pizza Com Parma
  +Monte do seu Jeito
  }
  <color:white> space
  Status da Entrega : <color:orange> A Caminho
  
     <&home> ..................<&person>....................... <&flag>
  
  Total: R$ 150,50 
}

[  Voltar             ]
}
@endsalt