# Generated by Django 4.2.20 on 2025-06-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skydrop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoruser',
            name='endereco',
            field=models.CharField(default='Av. Armando Lombardi, 940 - Barra da Tijuca', max_length=255),
            preserve_default=False,
        ),
    ]
