# Generated by Django 4.2.20 on 2025-06-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skydrop', '0002_vendoruser_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='localizacao_atual',
        ),
        migrations.RemoveField(
            model_name='drone',
            name='nivel_bateria',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('entregue', 'Entregue'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='drone',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('entregando', 'Entregando')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], max_length=20),
        ),
    ]
