# Generated by Django 4.2.20 on 2025-06-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skydrop', '0003_remove_drone_localizacao_atual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('entregando', 'Entregando'), ('entregue', 'Entregue'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], max_length=20),
        ),
    ]
