# Generated by Django 4.2.20 on 2025-06-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skydrop', '0004_alter_delivery_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
